# Generated by Django 5.2 on 2025-05-28 06:44

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255, null=True)),
                ('job_title', models.CharField(max_length=255, null=True)),
                ('rank', models.IntegerField(choices=[(3, '3'), (4, '4'), (5, '5'), (6, '6')], default=3)),
                ('money_per_hour', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('work_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=255, null=True)),
                ('work_name', models.CharField(max_length=255, unique=True)),
                ('type_material', models.CharField(blank=True, max_length=255, null=True)),
                ('usage_material', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('standard_time', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
        ),
        migrations.CreateModel(
            name='Piecework',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_work', models.CharField(choices=[('84', '84'), ('29', '29'), ('ТҮГ', 'ТҮГ'), ('Нөөц', 'Нөөц'), ('Депо', 'Депо')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('amount_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('amount_material', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('work_date', models.DateField(default=datetime.date.today)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employee.work')),
            ],
        ),
        migrations.CreateModel(
            name='DailySalary',
            fields=[
                ('salary_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('hours_per_day', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('salary_day', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('salary_date', models.DateField(default=datetime.date.today)),
                ('record_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'unique_together': {('employee', 'salary_date')},
            },
        ),
    ]
