# Generated by Django 5.2 on 2025-07-04 00:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Механик', 'Механик'), ('Авто хяналтын бүс (АКП)', 'Авто хяналтын бүс (АКП)'), ('Засвар 1', 'Засвар 1'), ('Засвар 2', 'Засвар 2'), ('Хос дугуй', 'Хос дугуй'), ('Тэргэнцэр', 'Тэргэнцэр'), ('Автоугсраа', 'Авто угсраа')], max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='work',
            name='standard_time',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
