# Generated by Django 5.2.12 on 2026-04-30 03:09

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalary',
            name='department',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='dailysalary',
            name='salary_date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='department',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='type_work',
            field=models.CharField(choices=[('84', '84'), ('29', '29'), ('79', '79'), ('03', '03'), ('ТҮГ', 'ТҮГ'), ('Нөөц', 'Нөөц'), ('Бүтээгдэхүүн', 'Бүтээгдэхүүн')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicaldailysalary',
            name='department',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaldailysalary',
            name='salary_date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='historicaldailywork',
            name='department',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaldailywork',
            name='type_work',
            field=models.CharField(choices=[('84', '84'), ('29', '29'), ('79', '79'), ('03', '03'), ('ТҮГ', 'ТҮГ'), ('Нөөц', 'Нөөц'), ('Бүтээгдэхүүн', 'Бүтээгдэхүүн')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalpiecework',
            name='department',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalpiecework',
            name='type_work',
            field=models.CharField(choices=[('84', '84'), ('29', '29'), ('79', '79'), ('03', '03'), ('ТҮГ', 'ТҮГ'), ('Нөөц', 'Нөөц'), ('Бүтээгдэхүүн', 'Бүтээгдэхүүн')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='type_material',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='piecework',
            name='department',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='piecework',
            name='type_work',
            field=models.CharField(choices=[('84', '84'), ('29', '29'), ('79', '79'), ('03', '03'), ('ТҮГ', 'ТҮГ'), ('Нөөц', 'Нөөц'), ('Бүтээгдэхүүн', 'Бүтээгдэхүүн')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='work',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='type_material',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='dailysalary',
            index=models.Index(fields=['department', 'salary_date'], name='employee_da_departm_5e88d3_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysalary',
            index=models.Index(fields=['-record_date'], name='employee_da_record__18818d_idx'),
        ),
        migrations.AddIndex(
            model_name='dailywork',
            index=models.Index(fields=['department', 'work_date'], name='employee_da_departm_3c9db9_idx'),
        ),
        migrations.AddIndex(
            model_name='dailywork',
            index=models.Index(fields=['work_date'], name='employee_da_work_da_1ff23e_idx'),
        ),
        migrations.AddIndex(
            model_name='dailywork',
            index=models.Index(fields=['-record_date'], name='employee_da_record__adc7a5_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_deleted', 'department', 'job_title', 'employee_id'], name='employee_em_is_dele_28e5f0_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id', 'is_deleted'], name='employee_em_employe_a4635c_idx'),
        ),
        migrations.AddIndex(
            model_name='piecework',
            index=models.Index(fields=['department', 'work_date'], name='employee_pi_departm_860fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='piecework',
            index=models.Index(fields=['employee', 'work_date'], name='employee_pi_employe_a40299_idx'),
        ),
        migrations.AddIndex(
            model_name='piecework',
            index=models.Index(fields=['work', 'work_date'], name='employee_pi_work_id_73c5db_idx'),
        ),
        migrations.AddIndex(
            model_name='piecework',
            index=models.Index(fields=['work_date', 'wagon_number'], name='employee_pi_work_da_b8be07_idx'),
        ),
        migrations.AddIndex(
            model_name='piecework',
            index=models.Index(fields=['-record_date'], name='employee_pi_record__9679aa_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['is_deleted', 'department', 'job_title', 'work_name'], name='employee_wo_is_dele_133193_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['department', 'work_name', 'is_deleted'], name='employee_wo_departm_41b938_idx'),
        ),
    ]
