# Generated by Django 5.2.12 on 2026-04-30 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_dailysalary_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='employee_em_is_dele_28e5f0_idx',
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_deleted', 'is_active', 'department', 'job_title', 'employee_id'], name='employee_em_is_dele_393cb7_idx'),
        ),
    ]
