# Generated by Django 5.2 on 2025-07-23 07:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Механик', 'Механик'), ('Авто хяналтын бүс (АКП)', 'Авто хяналтын бүс (АКП)'), ('Засвар 1', 'Засвар 1'), ('Засвар 2', 'Засвар 2'), ('Хос дугуй', 'Хос дугуй'), ('Тэргэнцэр', 'Тэргэнцэр'), ('Авто угсраа', 'Авто угсраа')], max_length=255),
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('master_id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('Механик', 'Механик'), ('Авто хяналтын бүс (АКП)', 'Авто хяналтын бүс (АКП)'), ('Засвар 1', 'Засвар 1'), ('Засвар 2', 'Засвар 2'), ('Хос дугуй', 'Хос дугуй'), ('Тэргэнцэр', 'Тэргэнцэр'), ('Авто угсраа', 'Авто угсраа')], max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
