# Generated by Django 5.2.12 on 2026-05-05 00:42

from django.db import migrations, models


def backfill_work_year_month(apps, schema_editor):
    Piecework = apps.get_model("employee", "Piecework")
    qs = Piecework.objects.filter(work_year__isnull=True).only("id", "work_date")
    to_update = []

    for p in qs.iterator(chunk_size=2000):
        p.work_year = p.work_date.year
        p.work_month = p.work_date.month
        to_update.append(p)
        if len(to_update) >= 2000:
            Piecework.objects.bulk_update(to_update, ["work_year", "work_month"])
            to_update.clear()

    if to_update:
        Piecework.objects.bulk_update(to_update, ["work_year", "work_month"])


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_employee_em_is_dele_28e5f0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpiecework',
            name='work_month',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalpiecework',
            name='work_year',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='piecework',
            name='work_month',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='piecework',
            name='work_year',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.RunPython(
            backfill_work_year_month,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='piecework',
            index=models.Index(fields=['employee', 'work_year', 'work_month'], name='employee_pi_employe_5dc04a_idx'),
        ),
    ]
