# Generated by Django 5.2.12 on 2026-05-05 03:19

from django.db import migrations, models


def backfill_work_year_month(apps, schema_editor):
    DailyWork = apps.get_model("employee", "DailyWork")
    qs = DailyWork.objects.filter(work_year__isnull=True).only("id", "work_date")
    to_update = []

    for daily_work in qs.iterator(chunk_size=2000):
        daily_work.work_year = daily_work.work_date.year
        daily_work.work_month = daily_work.work_date.month
        to_update.append(daily_work)

        if len(to_update) >= 2000:
            DailyWork.objects.bulk_update(to_update, ["work_year", "work_month"])
            to_update.clear()

    if to_update:
        DailyWork.objects.bulk_update(to_update, ["work_year", "work_month"])


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_historicalpiecework_work_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywork',
            name='work_month',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dailywork',
            name='work_year',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicaldailywork',
            name='work_month',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicaldailywork',
            name='work_year',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.RunPython(
            backfill_work_year_month,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='dailywork',
            index=models.Index(fields=['work_name', 'work_year', 'work_month'], name='employee_da_work_na_a822b7_idx'),
        ),
    ]
