# Generated by Django 5.2 on 2025-07-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_payroll'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailysalary',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dailysalary',
            constraint=models.UniqueConstraint(fields=('employee', 'salary_date'), name='unique_employee_salary_date'),
        ),
    ]
