# Generated by Django 5.2.12 on 2026-05-05 04:57

from django.db import migrations, models


def backfill_salary_year_month(apps, schema_editor):
    DailySalary = apps.get_model("employee", "DailySalary")
    qs = DailySalary.objects.filter(salary_year__isnull=True).only("id", "salary_date")
    to_update = []

    for daily_salary in qs.iterator(chunk_size=2000):
        daily_salary.salary_year = daily_salary.salary_date.year
        daily_salary.salary_month = daily_salary.salary_date.month
        to_update.append(daily_salary)

        if len(to_update) >= 2000:
            DailySalary.objects.bulk_update(
                to_update,
                ["salary_year", "salary_month"],
            )
            to_update.clear()

    if to_update:
        DailySalary.objects.bulk_update(to_update, ["salary_year", "salary_month"])


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_dailywork_work_month_dailywork_work_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalary',
            name='salary_month',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dailysalary',
            name='salary_year',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicaldailysalary',
            name='salary_month',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicaldailysalary',
            name='salary_year',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
        migrations.RunPython(
            backfill_salary_year_month,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='dailysalary',
            index=models.Index(fields=['employee', 'salary_year', 'salary_month'], name='employee_da_employe_fc8d9d_idx'),
        ),
    ]
