# Generated by Django 5.2 on 2025-08-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_dailysalary_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecework',
            name='wagon_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='department',
            field=models.CharField(max_length=255),
        ),
    ]
