# Generated by Django 5.2.12 on 2026-08-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_email_historicalemployee_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationRequest',
        ),
    ]
