# Generated by Django 5.2 on 2025-08-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_piecework_wagon_number_alter_employee_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecework',
            name='wagon_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
