# Generated by Django 5.2 on 2025-09-02 02:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_piecework_wagon_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecework',
            name='amount_time',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
