# Generated by Django 5.2.12 on 2026-08-18 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_delete_registrationrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('change_employee_status', 'Can activate or deactivate employee status')]},
        ),
    ]
