# Generated by Django 5.2.12 on 2026-08-18 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_employee_change_employee_status_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piecework',
            options={'permissions': [('view_material_report', 'Can view material usage report')]},
        ),
    ]
