# Generated by Django 5.2 on 2025-09-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_piecework_amount_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecework',
            name='group_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
