# Generated by Django 5.2 on 2025-09-04 03:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_piecework_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecework',
            name='amount_material',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='piecework',
            name='amount_time',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='work',
            name='standard_time',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='work',
            name='usage_material',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
