# Generated by Django 5.2 on 2025-09-04 06:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_piecework_amount_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='usage_material',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
