# Generated by Django 5.2.6 on 2025-09-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_work_usage_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='job_title',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.IntegerField(choices=[(3, 3), (4, 4), (5, 5), (6, 6)], default=3),
        ),
    ]
