# Generated by Django 5.2.12 on 2026-08-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_seed_view_employee_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysalary',
            options={'permissions': [('view_salary_amount', 'Can view salary amounts on daily salary records')]},
        ),
        migrations.AlterModelOptions(
            name='piecework',
            options={'permissions': [('view_material_report', 'Can view material usage report'), ('view_record_audit', 'Can view record creation metadata')]},
        ),
    ]
