# Generated by Django 5.2.6 on 2025-10-07 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_work_job_title_alter_employee_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='type_wagon',
            field=models.CharField(blank=True, choices=[('Хагас-84', 'Хагас-84'), ('Чингэлэг', 'Чингэлэг'), ('Тавцант', 'Тавцант'), ('Битүү', 'Битүү'), ('Хоппер-Дозатор', 'Хоппер-Дозатор'), ('Думпкар', 'Думпкар'), ('Цистерн', 'Цистерн'), ('Тусгай хэрэгцээний', 'Тусгай хэрэгцээний'), ('Их засвар', 'Их засвар'), ('Урсгал', 'Урсгал')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('Токарьчин', 'Токарьчин'), ('Бэлтгэл токарьчин', 'Бэлтгэл токарьчин'), ('Дархан лантуучин', 'Дархан лантуучин'), ('Гагнуурчин', 'Гагнуурчин'), ('Засварчин', 'Засварчин'), ('Будагчин', 'Будагчин'), ('Нээлхий', 'Нээлхий')], max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='money_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='piecework',
            name='type_work',
            field=models.CharField(choices=[('84', '84'), ('29', '29'), ('79', '79'), ('03', '03'), ('ТҮГ', 'ТҮГ'), ('Нөөц', 'Нөөц'), ('Бүтээгдэхүүн', 'Бүтээгдэхүүн')], max_length=50),
        ),
        migrations.AlterField(
            model_name='work',
            name='job_title',
            field=models.CharField(choices=[('Токарьчин', 'Токарьчин'), ('Бэлтгэл токарьчин', 'Бэлтгэл токарьчин'), ('Дархан лантуучин', 'Дархан лантуучин'), ('Гагнуурчин', 'Гагнуурчин'), ('Засварчин', 'Засварчин'), ('Будагчин', 'Будагчин'), ('Нээлхий', 'Нээлхий')], max_length=255),
        ),
    ]
