# Generated by Django 5.2.6 on 2025-10-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_work_type_wagon_alter_employee_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecework',
            name='job_title',
            field=models.CharField(choices=[('Токарьчин', 'Токарьчин'), ('Бэлтгэл токарьчин', 'Бэлтгэл токарьчин'), ('Дархан лантуучин', 'Дархан лантуучин'), ('Гагнуурчин', 'Гагнуурчин'), ('Засварчин', 'Засварчин'), ('Будагчин', 'Будагчин'), ('Нээлхий', 'Нээлхий')], db_index=True, default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piecework',
            name='type_wagon',
            field=models.CharField(blank=True, choices=[('Хагас-84', 'Хагас-84'), ('Чингэлэг', 'Чингэлэг'), ('Тавцант', 'Тавцант'), ('Битүү', 'Битүү'), ('Хоппер-Дозатор', 'Хоппер-Дозатор'), ('Думпкар', 'Думпкар'), ('Цистерн', 'Цистерн'), ('Тусгай хэрэгцээний', 'Тусгай хэрэгцээний'), ('Их засвар', 'Их засвар'), ('Урсгал', 'Урсгал')], db_index=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.CheckConstraint(condition=models.Q(('department__in', ('Засвар 1', 'Засвар 2')), ('type_wagon__isnull', True), _connector='OR'), name='type_wagon_only_for_allowed_departments'),
        ),
    ]
