# Generated by Django 5.2.12 on 2026-08-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_seed_view_and_audit_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('change_employee_status', 'Can activate or deactivate employee status'), ('select_department', 'Can browse any department')]},
        ),
    ]
