# Generated by Django 5.2.6 on 2025-10-22 05:35

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_piecework_job_title_piecework_type_wagon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(choices=[('Токарьчин', 'Токарьчин'), ('Бэлтгэл токарьчин', 'Бэлтгэл токарьчин'), ('Дархан лантуучин', 'Дархан лантуучин'), ('Гагнуурчин', 'Гагнуурчин'), ('Засварчин', 'Засварчин'), ('Будагчин', 'Будагчин'), ('Нээлхий', 'Нээлхий')], db_index=True, max_length=255)),
                ('type_work', models.CharField(choices=[('84', '84'), ('29', '29'), ('79', '79'), ('03', '03'), ('ТҮГ', 'ТҮГ'), ('Нөөц', 'Нөөц'), ('Бүтээгдэхүүн', 'Бүтээгдэхүүн')], max_length=50)),
                ('wagon_number', models.CharField(blank=True, max_length=50, null=True)),
                ('type_wagon', models.CharField(blank=True, choices=[('Хагас-84', 'Хагас-84'), ('Чингэлэг', 'Чингэлэг'), ('Тавцант', 'Тавцант'), ('Битүү', 'Битүү'), ('Хоппер-Дозатор', 'Хоппер-Дозатор'), ('Думпкар', 'Думпкар'), ('Цистерн', 'Цистерн'), ('Тусгай хэрэгцээний', 'Тусгай хэрэгцээний'), ('Их засвар', 'Их засвар'), ('Урсгал', 'Урсгал')], db_index=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_time', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_material', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('work_date', models.DateField(default=datetime.date.today)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employee.work')),
            ],
        ),
    ]
