# Generated by Django 5.2.6 on 2025-10-22 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_dailywork'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecework',
            name='daily_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieceworks', to='employee.dailywork'),
        ),
    ]
