# Generated by Django 5.2.6 on 2025-10-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_piecework_daily_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.UniqueConstraint(fields=('department', 'work_name'), name='unique_work_name_per_department'),
        ),
    ]
