# Generated by Django 5.2.6 on 2025-12-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_alter_work_work_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalary',
            name='employee_name',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
    ]
