# Generated by Django 5.2.6 on 2025-12-05 04:15

from django.db import migrations


def forwards(apps, schema_editor):
    DailySalary = apps.get_model('employee', 'DailySalary')

    qs = DailySalary.objects.filter(employee_name__isnull=True).select_related('employee')
    objs = []
    for ds in qs:
        try:
            name = ds.employee.name if ds.employee_id and ds.employee else None
        except Exception:
            name = None
        ds.employee_name = name
        objs.append(ds)
    if objs:
        DailySalary.objects.bulk_update(objs, ['employee_name'])


def reverse(apps, schema_editor):
    DailySalary = apps.get_model('employee', 'DailySalary')

    DailySalary.objects.update(employee_name=None)


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_dailysalary_employee_name'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=reverse),
    ]
