# Generated by Django 5.2.6 on 2025-12-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_backfill_dailysalary_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalary',
            name='employee_name',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
    ]
