# Generated by Django 5.2.6 on 2025-12-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_alter_dailysalary_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalary',
            name='department',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
    ]
