# Generated by Django 5.2.6 on 2025-12-05 06:11

from django.db import migrations


def forwards(apps, schema_editor):
    DailySalary = apps.get_model('employee', 'DailySalary')
    Employee = apps.get_model('employee', 'Employee')

    qs = DailySalary.objects.filter(department__isnull=True).select_related('employee')
    objs = []
    batch_size = 500

    for ds in qs.iterator():
        try:
            dept = ds.employee.department if ds.employee_id and ds.employee else None
        except Exception:
            dept = None
        ds.department = dept
        objs.append(ds)

        if len(objs) >= batch_size:
            DailySalary.objects.bulk_update(objs, ['department'])
            objs = []

    if objs:
        DailySalary.objects.bulk_update(objs, ['department'])


def reverse(apps, schema_editor):
    DailySalary = apps.get_model('employee', 'DailySalary')
    DailySalary.objects.update(department=None)


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_dailysalary_department'),
    ]

    operations = [
    ]
