# Generated by Django 5.2.6 on 2025-12-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_backfill_dailysalary_department_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalary',
            name='department',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
    ]
