# Generated by Django 5.2.6 on 2025-12-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_alter_dailysalary_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywork',
            name='department',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailywork',
            name='work_name',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
    ]
