# Generated by Django 5.2.6 on 2025-12-05 06:56

from django.db import migrations


def forwards(apps, schema_editor):
    DailyWork = apps.get_model('employee', 'DailyWork')
    qs = DailyWork.objects.filter(work_name__isnull=True).select_related('work')
    objs = []
    batch_size = 500

    for dw in qs.iterator():
        try:
            w = dw.work
            name = w.work_name if w else None
            dept = w.department if w else None
        except Exception:
            name = None
            dept = None
        dw.work_name = name
        dw.department = dept
        objs.append(dw)
        if len(objs) >= batch_size:
            DailyWork.objects.bulk_update(objs, ['work_name', 'department'])
            objs = []
    if objs:
        DailyWork.objects.bulk_update(objs, ['work_name', 'department'])


def reverse(apps, schema_editor):
    DailyWork = apps.get_model('employee', 'DailyWork')
    DailyWork.objects.update(work_name=None, department=None)


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_dailywork_department_dailywork_work_name'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=reverse),
    ]
