# Generated by Django 5.2.6 on 2025-12-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_backfill_dailywork_workname_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywork',
            name='department',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='work_name',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
    ]
