# Generated by Django 5.2.6 on 2025-12-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_alter_dailywork_department_alter_dailywork_work_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecework',
            name='department',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='piecework',
            name='employee_name',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='piecework',
            name='work_name',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
    ]
