# Generated by Django 5.2.6 on 2025-12-05 07:40

from django.db import migrations


def forwards(apps, schema_editor):
    Piecework = apps.get_model('employee', 'Piecework')
    qs = Piecework.objects.filter(employee_name__isnull=True).select_related('employee', 'work')
    objs = []
    batch = 500
    for pw in qs.iterator():
        pw.employee_name = pw.employee.name if pw.employee_id and pw.employee else None
        pw.work_name = pw.work.work_name if pw.work_id and pw.work else None
        # prefer employee.department
        pw.department = pw.employee.department if pw.employee_id and pw.employee else None
        objs.append(pw)
        if len(objs) >= batch:
            Piecework.objects.bulk_update(objs, ['employee_name', 'work_name', 'department'])
            objs = []
    if objs:
        Piecework.objects.bulk_update(objs, ['employee_name', 'work_name', 'department'])


def reverse(apps, schema_editor):
    Piecework = apps.get_model('employee', 'Piecework')
    Piecework.objects.update(employee_name=None, work_name=None, department=None)

class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0029_piecework_department_piecework_employee_name_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=reverse),
    ]
