# Generated by Django 5.2.6 on 2025-12-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0030_backfill_piecework_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecework',
            name='department',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='piecework',
            name='employee_name',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='piecework',
            name='work_name',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
    ]
