# Generated by Django 5.2.12 on 2026-04-06 01:56

import datetime
import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0031_alter_piecework_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalary',
            name='hours_per_day',
            field=models.IntegerField(default=11, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='amount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='amount_time',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000001'), editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Авто угсраа', 'Авто угсраа'), ('Авто хяналтын бүс (АКП)', 'Авто хяналтын бүс (АКП)'), ('Засвар 1', 'Засвар 1'), ('Засвар 2', 'Засвар 2'), ('Механик', 'Механик'), ('Тэргэнцэр', 'Тэргэнцэр'), ('Хос дугуй', 'Хос дугуй')], max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(error_messages={'unique': 'Must be unique.'}, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='money_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='master',
            name='department',
            field=models.CharField(choices=[('Авто угсраа', 'Авто угсраа'), ('Авто хяналтын бүс (АКП)', 'Авто хяналтын бүс (АКП)'), ('Засвар 1', 'Засвар 1'), ('Засвар 2', 'Засвар 2'), ('Механик', 'Механик'), ('Тэргэнцэр', 'Тэргэнцэр'), ('Хос дугуй', 'Хос дугуй')], max_length=255),
        ),
        migrations.AlterField(
            model_name='piecework',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='piecework',
            name='amount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='piecework',
            name='amount_time',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000001'), editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='work',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='work',
            name='standard_time',
            field=models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.CreateModel(
            name='HistoricalDailyWork',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('job_title', models.CharField(choices=[('Токарьчин', 'Токарьчин'), ('Бэлтгэл токарьчин', 'Бэлтгэл токарьчин'), ('Дархан лантуучин', 'Дархан лантуучин'), ('Гагнуурчин', 'Гагнуурчин'), ('Засварчин', 'Засварчин'), ('Будагчин', 'Будагчин'), ('Нээлхий', 'Нээлхий')], db_index=True, max_length=255)),
                ('work_name', models.CharField(blank=True, db_index=True, editable=False, max_length=255)),
                ('department', models.CharField(blank=True, db_index=True, editable=False, max_length=255)),
                ('type_work', models.CharField(choices=[('84', '84'), ('29', '29'), ('79', '79'), ('03', '03'), ('ТҮГ', 'ТҮГ'), ('Нөөц', 'Нөөц'), ('Бүтээгдэхүүн', 'Бүтээгдэхүүн')], max_length=50)),
                ('wagon_number', models.CharField(blank=True, max_length=50, null=True)),
                ('type_wagon', models.CharField(blank=True, choices=[('Хагас-84', 'Хагас-84'), ('Чингэлэг', 'Чингэлэг'), ('Тавцант', 'Тавцант'), ('Битүү', 'Битүү'), ('Хоппер-Дозатор', 'Хоппер-Дозатор'), ('Думпкар', 'Думпкар'), ('Цистерн', 'Цистерн'), ('Тусгай хэрэгцээний', 'Тусгай хэрэгцээний'), ('Их засвар', 'Их засвар'), ('Урсгал', 'Урсгал')], db_index=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('amount_time', models.DecimalField(decimal_places=6, default=Decimal('0.000001'), editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('amount_price', models.DecimalField(decimal_places=2, default=Decimal('0.01'), editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('amount_material', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('work_date', models.DateField(default=datetime.date.today)),
                ('record_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.work')),
            ],
            options={
                'verbose_name': 'historical daily work',
                'verbose_name_plural': 'historical daily works',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
