# Generated by Django 5.2.12 on 2026-04-06 06:45

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0033_historicaldailysalary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWork',
            fields=[
                ('work_id', models.IntegerField(blank=True, db_index=True, editable=False)),
                ('department', models.CharField(max_length=255)),
                ('job_title', models.CharField(choices=[('Токарьчин', 'Токарьчин'), ('Бэлтгэл токарьчин', 'Бэлтгэл токарьчин'), ('Дархан лантуучин', 'Дархан лантуучин'), ('Гагнуурчин', 'Гагнуурчин'), ('Засварчин', 'Засварчин'), ('Будагчин', 'Будагчин'), ('Нээлхий', 'Нээлхий')], max_length=255)),
                ('work_name', models.CharField(max_length=255)),
                ('type_wagon', models.CharField(blank=True, choices=[('Хагас-84', 'Хагас-84'), ('Чингэлэг', 'Чингэлэг'), ('Тавцант', 'Тавцант'), ('Битүү', 'Битүү'), ('Хоппер-Дозатор', 'Хоппер-Дозатор'), ('Думпкар', 'Думпкар'), ('Цистерн', 'Цистерн'), ('Тусгай хэрэгцээний', 'Тусгай хэрэгцээний'), ('Их засвар', 'Их засвар'), ('Урсгал', 'Урсгал')], max_length=100, null=True)),
                ('type_material', models.CharField(blank=True, max_length=255, null=True)),
                ('usage_material', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('standard_time', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical work',
                'verbose_name_plural': 'historical works',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
