# Generated by Django 5.2.12 on 2026-04-07 06:30

import datetime
import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0037_historicalpayroll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPiecework',
            fields=[
                ('record_id', models.IntegerField(blank=True, db_index=True)),
                ('employee_name', models.CharField(blank=True, db_index=True, editable=False, max_length=255)),
                ('department', models.CharField(blank=True, db_index=True, editable=False, max_length=255)),
                ('job_title', models.CharField(choices=[('Токарьчин', 'Токарьчин'), ('Бэлтгэл токарьчин', 'Бэлтгэл токарьчин'), ('Дархан лантуучин', 'Дархан лантуучин'), ('Гагнуурчин', 'Гагнуурчин'), ('Засварчин', 'Засварчин'), ('Будагчин', 'Будагчин'), ('Нээлхий', 'Нээлхий')], db_index=True, max_length=255)),
                ('work_name', models.CharField(blank=True, db_index=True, editable=False, max_length=255)),
                ('type_work', models.CharField(choices=[('84', '84'), ('29', '29'), ('79', '79'), ('03', '03'), ('ТҮГ', 'ТҮГ'), ('Нөөц', 'Нөөц'), ('Бүтээгдэхүүн', 'Бүтээгдэхүүн')], max_length=50)),
                ('wagon_number', models.CharField(blank=True, max_length=50, null=True)),
                ('type_wagon', models.CharField(blank=True, choices=[('Хагас-84', 'Хагас-84'), ('Чингэлэг', 'Чингэлэг'), ('Тавцант', 'Тавцант'), ('Битүү', 'Битүү'), ('Хоппер-Дозатор', 'Хоппер-Дозатор'), ('Думпкар', 'Думпкар'), ('Цистерн', 'Цистерн'), ('Тусгай хэрэгцээний', 'Тусгай хэрэгцээний'), ('Их засвар', 'Их засвар'), ('Урсгал', 'Урсгал')], db_index=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('amount_time', models.DecimalField(decimal_places=6, default=Decimal('0.000001'), editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('amount_price', models.DecimalField(decimal_places=2, default=Decimal('0.01'), editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('amount_material', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('work_date', models.DateField(default=datetime.date.today)),
                ('record_date', models.DateTimeField(blank=True, editable=False)),
                ('group_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('daily_work', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.dailywork')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.work')),
            ],
            options={
                'verbose_name': 'historical piecework',
                'verbose_name_plural': 'historical pieceworks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
