# Generated by Django 5.2.12 on 2026-04-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0038_historicalpiecework'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='work',
            name='unique_work_name_per_department',
        ),
        migrations.AddField(
            model_name='historicalwork',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('department', 'work_name'), name='unique_work_name_per_department'),
        ),
    ]
