# Generated by Django 5.2.12 on 2026-04-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0039_remove_work_unique_work_name_per_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
