# Generated by Django 5.2.12 on 2026-04-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0040_employee_is_deleted_historicalemployee_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayroll',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='payroll',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
