# Generated by Django 5.2.12 on 2026-04-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0041_historicalpayroll_is_deleted_payroll_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaster',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='master',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
