from .home_views import *
from .employee_views import *
from .work_views import *
from .monthly_salary_views import *
from .piecework_views import *
from .employee_salary_views import *
from .calculation_materials import *
from .employee_salaries_excel import *
from .employee_salaries_pdf import *
