import {
  DUPLICATE_SCROLL,
  DUPLICATE_TAGS,
  DUPLICATE_TEXT,
  type ExistingPiecework,
  formatEmployeeDisplay,
  getDuplicateById,
  normalizeWagon,
  openDuplicateModal,
  parseJsonScript,
  setDuplicateText,
  setupDuplicateModalClose,
} from "./duplicate_check";

const PW_DUPLICATE_SELECTORS = {
  existingScript: "existing-pieceworks",
  form: "createForm",
  modal: "saveDuplicateModal",
  modalCancel: "[data-modal-cancel]",
  employeeCheckbox: 'input[name="employee_ids"]:checked',
  workCheckbox: 'input[name="work_ids"]:checked',
  workDate: "work_date",
  wagonNumber: "wagon_number",
} as const;

const PW_DUPLICATE_ELEMENTS = {
  amountError: "amount-error",
  elIdTypeWork: "id_type_work",
  detailEmployee: "duplicateDetailEmployee",
  detailWork: "duplicateDetailWork",
  detailTypeWork: "duplicateDetailTypeWork",
  detailWagonNumber: "duplicateDetailWagonNumber",
  detailWorkDate: "duplicateDetailWorkDate",
} as const;

const PW_DUPLICATE_ATTRS = {
  empId: "data-emp-id",
  empName: "data-emp-name",
  workName: "data-work-name",
} as const;

/**
 * Creates a unique key
 */
function makeDuplicateKey(
  keyEmpId: string,
  keyWorkId: string,
  keyTypeWork: string,
  keyWorkDate: string,
  keyWagonNumber: string | null,
): string {
  return `${keyEmpId}::${keyWorkId}::${keyTypeWork}::${keyWorkDate}::${keyWagonNumber ?? ""}`;
}

/**
 * Generates a unique key
 */
function makeDuplicateKeyFrom(pw: ExistingPiecework): string {
  const wagon = normalizeWagon(pw.wagon_number);
  return makeDuplicateKey(
    String(pw.employee_code),
    String(pw.work_id),
    pw.type_work,
    pw.work_date,
    wagon,
  );
}

/* Initialization */
document.addEventListener("DOMContentLoaded", () => {
  const existing = parseJsonScript<ExistingPiecework>(
    PW_DUPLICATE_SELECTORS.existingScript,
  );
  const existingSet = new Set(existing.map(makeDuplicateKeyFrom));
  const form = getDuplicateById(
    PW_DUPLICATE_SELECTORS.form,
  ) as HTMLFormElement | null;
  const modalDiv = getDuplicateById(PW_DUPLICATE_SELECTORS.modal);

  if (!form || !modalDiv) return;

  setupDuplicateModalClose(modalDiv, PW_DUPLICATE_SELECTORS.modalCancel);

  /**
   * Core validation logic triggered on form submission.
   */
  form.addEventListener("submit", (event) => {
    // Stop check if UI already shows an 'Amount' validation error (prevents multiple error types at once)
    const amountErrorEl = document.getElementById(
      PW_DUPLICATE_ELEMENTS.amountError,
    );
    if (amountErrorEl) {
      event.preventDefault();
      amountErrorEl.scrollIntoView(DUPLICATE_SCROLL);
      return;
    }

    // Gather selected employee and work IDs from the form checkboxes
    const employeeCheckboxes = Array.from(
      document.querySelectorAll<HTMLInputElement>(
        PW_DUPLICATE_SELECTORS.employeeCheckbox,
      ),
    );
    const workCheckboxes = Array.from(
      document.querySelectorAll<HTMLInputElement>(
        PW_DUPLICATE_SELECTORS.workCheckbox,
      ),
    );

    const selectedEmpIds = employeeCheckboxes.map((checkbox) => checkbox.value);
    const selectedWorkIds = workCheckboxes.map((checkbox) => checkbox.value);

    // Find the work type field using multiple possible ID/Name variations generated by Django
    const typeWorkEl = getDuplicateById(PW_DUPLICATE_ELEMENTS.elIdTypeWork) as
      | HTMLInputElement
      | HTMLSelectElement
      | null;
    if (!typeWorkEl) return;

    const workDateEl = getDuplicateById(
      PW_DUPLICATE_SELECTORS.workDate,
    ) as HTMLInputElement | null;
    if (!workDateEl) return;

    const wagonNumberInput = getDuplicateById(
      PW_DUPLICATE_SELECTORS.wagonNumber,
    ) as HTMLInputElement | null;

    const typeWork = typeWorkEl.value;
    const workDate = workDateEl.value;
    const wagon = normalizeWagon(wagonNumberInput?.value);

    // Basic exit if selections are missing
    if (selectedEmpIds.length === 0 || selectedWorkIds.length === 0) return;

    // Compare every selected Employee + Work combination against existing records
    const duplicatePairs: Array<{ empId: string; workId: string }> = [];

    for (const empId of selectedEmpIds) {
      for (const workId of selectedWorkIds) {
        if (
          existingSet.has(
            makeDuplicateKey(empId, workId, typeWork, workDate, wagon),
          )
        ) {
          duplicatePairs.push({ empId, workId });
        }
      }
    }

    // Proceed with standard submission if no duplicates were found
    if (duplicatePairs.length === 0) return;

    // Duplicates found: Prevent submission and prepare modal data
    event.preventDefault();

    // Unique sets for faster filtering of names
    const dupEmpIds = new Set(
      duplicatePairs.map((piecework) => piecework.empId),
    );
    const dupWorkIds = new Set(
      duplicatePairs.map((piecework) => piecework.workId),
    );

    // Resolve employee names/IDs from table attributes for the error summary
    const selectedEmployees = employeeCheckboxes
      .filter((checkbox) => dupEmpIds.has(checkbox.value))
      .map((checkbox) => {
        const tr = checkbox.closest(DUPLICATE_TAGS.tableRow);
        const id = (
          tr?.getAttribute(PW_DUPLICATE_ATTRS.empId) ?? checkbox.value
        ).trim();
        const name = (
          tr?.getAttribute(PW_DUPLICATE_ATTRS.empName) ?? ""
        ).trim();
        return formatEmployeeDisplay(id, name);
      });

    // Resolve work names from data-attributes for the error summary
    const selectedWorks = Array.from(
      new Set(
        workCheckboxes
          .filter((checkbox) => dupWorkIds.has(checkbox.value))
          .map((checkbox) => {
            const tr = checkbox.closest(DUPLICATE_TAGS.tableRow);
            return (
              checkbox.getAttribute(PW_DUPLICATE_ATTRS.workName)?.trim() ||
              tr?.getAttribute(PW_DUPLICATE_ATTRS.workName)?.trim() ||
              ""
            );
          })
          .filter(Boolean),
      ),
    );

    // Populate the modal with details about why the submission was blocked
    setDuplicateText(
      PW_DUPLICATE_ELEMENTS.detailEmployee,
      selectedEmployees.join(", "),
    );
    setDuplicateText(
      PW_DUPLICATE_ELEMENTS.detailWork,
      selectedWorks.join(", "),
    );
    setDuplicateText(PW_DUPLICATE_ELEMENTS.detailTypeWork, typeWork);
    setDuplicateText(
      PW_DUPLICATE_ELEMENTS.detailWagonNumber,
      wagon ?? DUPLICATE_TEXT.emptyWagonNumber,
    );
    setDuplicateText(PW_DUPLICATE_ELEMENTS.detailWorkDate, workDate);

    openDuplicateModal(modalDiv);
  });
});
