name: Django CI

on:
  push:
    branches: 
      - "feature/replace-bootstrap-with-tailwind"
      - "upgrade/django-5.2.9"
      - "vite-javascript"
      - "transition-to-typescript"
  pull_request:
    branches:
      - "feature/replace-bootstrap-with-tailwind"
      - "upgrade/django-5.2.9"
      - "vite-javascript"
      - "transition-to-typescript"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
        run: |
          python manage.py test
